### ISSUE TITLE
Error: Binary request timed out. 

### ISSUE THREAD

**Issue by shuxiao9058** [codota/tabnine-vscode#1091]
Unable to resolve your shell environment: Unexpected exit code from spawned shell (code null, signal SIGBUS)

ERR [Extension Host] TypeError: Cannot read properties of undefined (reading 'assets')
	at /Users/jiya/.vscode/extensions/tabnine.tabnine-vscode-3.6.45/out/extension.js:17:105903
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.default (/Users/jiya/.vscode/extensions/tabnine.tabnine-vscode-3.6.45/out/extension.js:17:105811)
console.ts:137 [Extension Host] TypeError: Cannot read properties of undefined (reading 'assets')
	at /Users/jiya/.vscode/extensions/tabnine.tabnine-vscode-3.6.45/out/extension.js:17:105903
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.default (/Users/jiya/.vscode/extensions/tabnine.tabnine-vscode-3.6.45/out/extension.js:17:105811)
T @ console.ts:137
log.ts:441   ERR [Extension Host] Error: Binary request timed out. {"State":{}}
	at Timeout._onTimeout (/Users/jiya/.vscode/extensions/tabnine.tabnine-vscode-3.6.45/out/extension.js:17:33113)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
console.ts:137 [Extension Host] Error: Binary request timed out. {"State":{}}
	at Timeout._onTimeout (/Users/jiya/.vscode/extensions/tabnine.tabnine-vscode-3.6.45/out/extension.js:17:33113)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
T @ console.ts:137

gz#23204<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/23204'>Zendesk ticket #23204</a>)</i>

**Comment by TzufTabnine** [comment]
@shuxiao9058 

Please sen here the log files. See [here](https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Tabnine-Logs-on-VSCode) how to do that.

**Comment by shuxiao9058** [comment]
```
023-06-02 13:57:41.129 [info] [vscode-org-mode.org-mode]: Command `org.decrementContext` appears multiple times in the `commands` section.
2023-06-02 13:57:41.129 [info] [vscode-org-mode.org-mode]: Command `org.bold` appears multiple times in the `commands` section.
2023-06-02 13:57:41.129 [info] [vscode-org-mode.org-mode]: Command `org.italic` appears multiple times in the `commands` section.
2023-06-02 13:57:41.129 [info] [vscode-org-mode.org-mode]: Command `org.underline` appears multiple times in the `commands` section.
2023-06-02 13:57:41.129 [info] [vscode-org-mode.org-mode]: Command `org.code` appears multiple times in the `commands` section.
2023-06-02 13:57:41.129 [info] [vscode-org-mode.org-mode]: Command `org.verbose` appears multiple times in the `commands` section.
2023-06-02 13:57:41.129 [info] [vscode-org-mode.org-mode]: Command `org.literal` appears multiple times in the `commands` section.
2023-06-02 13:57:41.129 [info] [vscode-org-mode.org-mode]: Command `org.butterfly` appears multiple times in the `commands` section.
2023-06-02 13:57:43.270 [info] [perf] Render performance baseline is 18ms
2023-06-02 13:57:44.917 [error] [Extension Host] Error: Binary request timed out. {"State":{}}
	at Timeout._onTimeout (/Users/jiya/.vscode/extensions/tabnine.tabnine-vscode-3.6.50/out/extension.js:17:33448)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
2023-06-02 13:57:52.207 [info] [vscode-org-mode.org-mode]: Command `org.insertHeadingRespectContent` appears multiple times in the `commands` section.
2023-06-02 13:57:52.207 [info] [vscode-org-mode.org-mode]: Command `org.insertSubheading` appears multiple times in the `commands` section.
2023-06-02 13:57:52.207 [info] [vscode-org-mode.org-mode]: Command `org.doDemote` appears multiple times in the `commands` section.
2023-06-02 13:57:52.207 [info] [vscode-org-mode.org-mode]: Command `org.doPromote` appears multiple times in the `commands` section.
2023-06-02 13:57:52.207 [info] [vscode-org-mode.org-mode]: Command `org.promoteSubtree` appears multiple times in the `commands` section.
2023-06-02 13:57:52.208 [info] [vscode-org-mode.org-mode]: Command `org.demoteSubtree` appears multiple times in the `commands` section.
2023-06-02 13:57:52.208 [info] [vscode-org-mode.org-mode]: Command `org.timestamp` appears multiple times in the `commands` section.
2023-06-02 13:57:52.208 [info] [vscode-org-mode.org-mode]: Command `org.clockin` appears multiple times in the `commands` section.
2023-06-02 13:57:52.208 [info] [vscode-org-mode.org-mode]: Command `org.clockout` appears multiple times in the `commands` section.
2023-06-02 13:57:52.208 [info] [vscode-org-mode.org-mode]: Command `org.updateclock` appears multiple times in the `commands` section.
2023-06-02 13:57:52.208 [info] [vscode-org-mode.org-mode]: Command `org.incrementContext` appears multiple times in the `commands` section.
2023-06-02 13:57:52.208 [info] [vscode-org-mode.org-mode]: Command `org.decrementContext` appears multiple times in the `commands` section.
2023-06-02 13:57:52.208 [info] [vscode-org-mode.org-mode]: Command `org.bold` appears multiple times in the `commands` section.
2023-06-02 13:57:52.208 [info] [vscode-org-mode.org-mode]: Command `org.italic` appears multiple times in the `commands` section.
2023-06-02 13:57:52.208 [info] [vscode-org-mode.org-mode]: Command `org.underline` appears multiple times in the `commands` section.
2023-06-02 13:57:52.208 [info] [vscode-org-mode.org-mode]: Command `org.code` appears multiple times in the `commands` section.
2023-06-02 13:57:52.208 [info] [vscode-org-mode.org-mode]: Command `org.verbose` appears multiple times in the `commands` section.
2023-06-02 13:57:52.208 [info] [vscode-org-mode.org-mode]: Command `org.literal` appears multiple times in the `commands` section.
2023-06-02 13:57:52.208 [info] [vscode-org-mode.org-mode]: Command `org.butterfly` appears multiple times in the `commands` section.
2023-06-02 13:57:52.251 [warning] No search provider registered for scheme: file, waiting
2023-06-02 13:57:52.446 [error] Extension 'tabnine.tabnine-vscode' wants API proposal 'inlineCompletions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-06-02 13:57:52.454 [info] [vscode-org-mode.org-mode]: Command `org.insertHeadingRespectContent` appears multiple times in the `commands` section.
2023-06-02 13:57:52.454 [info] [vscode-org-mode.org-mode]: Command `org.insertSubheading` appears multiple times in the `commands` section.
2023-06-02 13:57:52.454 [info] [vscode-org-mode.org-mode]: Command `org.doDemote` appears multiple times in the `commands` section.
2023-06-02 13:57:52.454 [info] [vscode-org-mode.org-mode]: Command `org.doPromote` appears multiple times in the `commands` section.
2023-06-02 13:57:52.455 [info] [vscode-org-mode.org-mode]: Command `org.promoteSubtree` appears multiple times in the `commands` section.
2023-06-02 13:57:52.455 [info] [vscode-org-mode.org-mode]: Command `org.demoteSubtree` appears multiple times in the `commands` section.
2023-06-02 13:57:52.455 [info] [vscode-org-mode.org-mode]: Command `org.timestamp` appears multiple times in the `commands` section.
2023-06-02 13:57:52.455 [info] [vscode-org-mode.org-mode]: Command `org.clockin` appears multiple times in the `commands` section.
2023-06-02 13:57:52.455 [info] [vscode-org-mode.org-mode]: Command `org.clockout` appears multiple times in the `commands` section.
2023-06-02 13:57:52.455 [info] [vscode-org-mode.org-mode]: Command `org.updateclock` appears multiple times in the `commands` section.
2023-06-02 13:57:52.455 [info] [vscode-org-mode.org-mode]: Command `org.incrementContext` appears multiple times in the `commands` section.
2023-06-02 13:57:52.455 [info] [vscode-org-mode.org-mode]: Command `org.decrementContext` appears multiple times in the `commands` section.
2023-06-02 13:57:52.456 [info] [vscode-org-mode.org-mode]: Command `org.bold` appears multiple times in the `commands` section.
2023-06-02 13:57:52.456 [info] [vscode-org-mode.org-mode]: Command `org.italic` appears multiple times in the `commands` section.
2023-06-02 13:57:52.456 [info] [vscode-org-mode.org-mode]: Command `org.underline` appears multiple times in the `commands` section.
2023-06-02 13:57:52.456 [info] [vscode-org-mode.org-mode]: Command `org.code` appears multiple times in the `commands` section.
2023-06-02 13:57:52.456 [info] [vscode-org-mode.org-mode]: Command `org.verbose` appears multiple times in the `commands` section.
2023-06-02 13:57:52.456 [info] [vscode-org-mode.org-mode]: Command `org.literal` appears multiple times in the `commands` section.
2023-06-02 13:57:52.456 [info] [vscode-org-mode.org-mode]: Command `org.butterfly` appears multiple times in the `commands` section.
2023-06-02 13:57:58.152 [error] [Extension Host] Error: Binary request timed out. {"State":{}}
	at Timeout._onTimeout (/Users/jiya/.vscode/extensions/tabnine.tabnine-vscode-3.6.47/out/extension.js:17:33448)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)

```

**Comment by TzufTabnine** [comment]
@shuxiao9058 Can you also send us Tabnine logs (The engine)?
See [here](https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Tabnine-Logs-on-VSCode) how to do that.

**Comment by shuxiao9058** [comment]
It seems because that I blocked the `notify.tabnine.com` domain.

**Comment by shuxiao9058** [comment]
[tabnine-vscode_rCURRENT.log-50620.txt](https://github.com/codota/tabnine-vscode/files/11654618/tabnine-vscode_rCURRENT.log-50620.txt)

**Comment by yCodeTech** [comment]
Please fix this. The intellisense doesn't work, just keeps saying it's loading. I've had to disable tabnine to get intellisense working again.

**Comment by TzufTabnine** [comment]
@yCodeTech 
Can you also send logs? See [here](https://support.tabnine.com/hc/en-us/articles/5283127765265-Getting-Tabnine-Logs-on-VSCode) how to do that.

**Comment by romanlex** [comment]
what about this issue?
