### ISSUE TITLE
TabNine requires log in despite being already logged in.

### ISSUE THREAD

**Issue by BladeMF** [codota/tabnine-vscode#1533]
**please complete the following information:**

- OS version: Win 11 24H2
- Editor version [e.g. 1.45.0-insider]: 1.95.3 (user setup)
- Programming language: N/A
- TabNine extension version: 3.199.0

**If the issue is related to TabNine failure, please provide log files:**

Type `TabNine::config` in your editor, the logs are located at the bottom of the page
```
06:47:28 GMT+0000 (Coordinated Universal Time) [INFO]: spawning binary with command: /root/.vscode-server/data/User/globalStorage/tabnine.tabnine-vscode/binaries/4.207.0/x86_64-unknown-linux-musl/TabNine args: --tls_config insecure=false --no-lsp=true --client=vscode --client-metadata clientVersion=1.95.3 pluginVersion=3.199.0 t9-vscode-AutoImportEnabled=true t9-vscode-TSAutoImportEnabled=true t9-vscode-JSAutoImportEnabled=true vscode-telemetry-enabled=true vscode-remote=true vscode-remote-name=dev-container vscode-extension-kind=2 vscode-theme-name=Default Dark+ vscode-theme-kind=Dark vscode-machine-id=f152457bbfc02f535085a90410e076b56a687910d73e1c931616d03203116552 vscode-is-new-app-install=false vscode-session-id=c0c7e282-dbdf-460e-8745-e333a2ffa4bc1733294828100 vscode-language=en vscode-app-name=Visual Studio Code vscode-beta-channel-enabled=false vscode-status-customization=unknown vscode-inline-api-enabled=true vscode-code-lens-enabled=true vscode-found-intellicode=false ide-restart-counter=0 

06:47:28 GMT+0000 (Coordinated Universal Time) [DEBUG]: capabilities resolved immediately 

06:47:29 GMT+0000 (Coordinated Universal Time) [ERROR]: Error: Binary request timed out. {"State":{}} 

06:47:31 GMT+0000 (Coordinated Universal Time) [ERROR]: Error: Binary request timed out. {"State":{}} 

06:47:32 GMT+0000 (Coordinated Universal Time) [DEBUG]: Updating root paths for project app [Dev Container: Tender Vault @ desktop-linux]: ["/var/www/html/app"] 
```

**Editor console logs:**

```
 WARN [mainThreadStorage] large extension state detected (extensionId: TabNine.tabnine-vscode, global: true): 6375.31640625kb. Consider to use 'storageUri' or 'globalStorageUri' to store this data on disk instead.

... 

  ERR command 'tabnine.chat.focus-input' not found: Error: command 'tabnine.chat.focus-input' not found
    at mWe.n (vscode-file://vscode-app/c:/Users/vladi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1295:1341)
    at mWe.executeCommand (vscode-file://vscode-app/c:/Users/vladi/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1295:1273)
```

**Issue Details:**
I have a "Sign in to use TabNine" propmt in the profile menu, but the menu also shows that I have signed in. When I click on this prompt the sign in process completes again and the message disappears. It happens at every start up.
<img width="538" alt="image" src="https://github.com/user-attachments/assets/52960207-d449-4068-be7a-233a84120062">

gz#37140<br><br><i>(related to <a href='https://tabninedesk.zendesk.com/agent/tickets/37140'>Zendesk ticket #37140</a>)</i>

**Comment by TzufTabnine** [comment]
@BladeMF  please delete Tabnine from your machine, reinstall, and try again. https://support.tabnine.com/hc/en-us/articles/17823949049745-How-to-delete-Tabnine-completely-from-your-machine
