### ISSUE TITLE
tabnine 3.2.14 not starting in vscode

### ISSUE THREAD

**Issue by hauselin** [codota/tabnine-vscode#442]
- OS version: Mac Catalina
- Editor version 1.54.3
- Programming language: Python
- TabNine extension version: 3.2.14

```
[Extension Host] stack trace: TypeError: Cannot read property 'os' of undefined    
at Object.getReportData [as default] (/Users/hause/.vscode/extensions/tabnine.tabnine-vscode-3.2.14/out/reports/reportData.js:32:22)    
at Object.report (/Users/hause/.vscode/extensions/tabnine.tabnine-vscode-3.2.14/out/reports/reporter.js:28:60)   
at Object.runProcess (/Users/hause/.vscode/extensions/tabnine.tabnine-vscode-3.2.14/out/binary/runProcess.js:12:16)    
at isValidBinary (/Users/hause/.vscode/extensions/tabnine.tabnine-vscode-3.2.14/out/binary/binaryFetcher/binaryValidator.js:11:45)   
at Object.asyncFind (/Users/hause/.vscode/extensions/tabnine.tabnine-vscode-3.2.14/out/utils.js:39:13)    
at Object.fetchBinaryPath [as default] (/Users/hause/.vscode/extensions/tabnine.tabnine-vscode-3.2.14/out/binary/binaryFetcher/index.js:14:29)    
at Object.runBinary [as default] (/Users/hause/.vscode/extensions/tabnine.tabnine-vscode-3.2.14/out/binary/runBinary.js:8:21)    
at Binary.startChild (/Users/hause/.vscode/extensions/tabnine.tabnine-vscode-3.2.14/out/binary/Binary.js:70:36)    
at backgroundInit (/Users/hause/.vscode/extensions/tabnine.tabnine-vscode-3.2.14/out/extension.js:41:5)
```

**Issue Details:**
After upgrading to `3.2.14` this morning, tabnine is failing to start in vscode.

<img width="161" alt="image" src="https://user-images.githubusercontent.com/7620977/112765806-1eeed100-8fcc-11eb-82a1-df586d0de9d8.png">

**Comment by enkeyz** [comment]
Same here. Looks like their servers are down.

**Comment by bilucodota** [comment]
Hi guys, thanks for reaching out. This is being taking care of. Will update ASAP.

**Comment by RitwickJoshi** [comment]
Literally had the same issue just now good to know others are having the same as well.
All the best to the DEVS to fix this bug.

**Comment by yonip23** [comment]
Hey all,
We released a new version (3.2.15) that contains a fix to this bug. please let us know if you still have any problems

**Comment by enkeyz** [comment]
> Hey all,
> We released a new version (3.2.15) that contains a fix to this bug. please let us know if you still have any problems

Works great.

**Comment by hauselin** [comment]
> Hey all,
> We released a new version (3.2.15) that contains a fix to this bug. please let us know if you still have any problems

Works for me too. Thanks for the quick fix!

**Comment by Jacksonmills** [comment]
working again ty!

**Comment by boaz-codota** [comment]
Sorry for that everyone. Don't release versions after [the 4th cup](https://en.wikipedia.org/wiki/Passover_Seder#:~:text=The%20Four%20Cups%20represent%20the,and%20%22I%20will%20take.%22).
