### ISSUE TITLE
tabnine 3.2.1.5 says enabled, error "not supported in arm64"

### ISSUE THREAD

**Issue by jwiede** [codota/tabnine-vscode#444]
**please complete the following information:**

- OS version: Nvidia JetPack 4.4 (Linux 4.9.140-tegra aarch64)
- Editor version: 1.54.3 
- Programming language: any
- TabNine extension version: 3.2.1.5

Unable to provide logs, TabNine says "enabled" but not visible in status bar, in newly-opened .c file neither "TabNine::config" nor "TabNine::version" produce _any results._  At **very least**, it should  show error in editor UI and clearly state it isn't supported (without having to dig into logs), not give every appearance of working normally.  

Realistically, arm64 (really aarch64) needs to be supported, extremely common embedded ML development platform (Nvidia Jetson Nano, Xavier, etc.).  Jetson offers decently GPU-equipped environment even on Nano to run models.  Additionally, lack of arm64/aarch64 support not clearly mentioned in obvious locations at website, and statements about supporting VSCode (which **does** support arm & aarch64) imply otherwise.

**Editor console logs:**

[2021-03-28 17:29:24.533] [exthost] [error] Activating extension TabNine.tabnine-vscode failed due to an error:
[2021-03-28 17:29:24.546] [exthost] [error] Error: Sorry, the architecture 'arm64' is not supported by TabNine.
	at getArch (/home/jwiede/.vscode/extensions/tabnine.tabnine-vscode-3.2.15/out/binary/paths.js:62:11)
	at Object.<anonymous> (/home/jwiede/.vscode/extensions/tabnine.tabnine-vscode-3.2.15/out/binary/paths.js:6:22)
	at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:3:12841)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.s._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27167)
	at Function._._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:23919)
	at Function.W._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/usr/share/code/resources/app/out/vs/loader.js:3:12287)
	at Object.<anonymous> (/home/jwiede/.vscode/extensions/tabnine.tabnine-vscode-3.2.15/out/binary/binaryFetcher/activeFileHandler.js:4:17)
	at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:3:12841)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.s._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27167)
	at Function._._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:23919)
	at Function.W._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/usr/share/code/resources/app/out/vs/loader.js:3:12287)
	at Object.<anonymous> (/home/jwiede/.vscode/extensions/tabnine.tabnine-vscode-3.2.15/out/binary/binaryFetcher/index.js:6:29)
	at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:3:12841)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.s._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27167)
	at Function._._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:23919)
	at Function.W._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/usr/share/code/resources/app/out/vs/loader.js:3:12287)
	at Object.<anonymous> (/home/jwiede/.vscode/extensions/tabnine.tabnine-vscode-3.2.15/out/binary/runBinary.js:4:25)
	at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:3:12841)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.s._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27167)
	at Function._._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:23919)
	at Function.W._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/usr/share/code/resources/app/out/vs/loader.js:3:12287)
	at Object.<anonymous> (/home/jwiede/.vscode/extensions/tabnine.tabnine-vscode-3.2.15/out/binary/Binary.js:5:21)
	at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:3:12841)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.s._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27167)
	at Function._._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:23919)
	at Function.W._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/usr/share/code/resources/app/out/vs/loader.js:3:12287)
	at Object.<anonymous> (/home/jwiede/.vscode/extensions/tabnine.tabnine-vscode-3.2.15/out/binary/requests/requests.js:4:18)
	at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:3:12841)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.s._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27167)
	at Function._._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:23919)
	at Function.W._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/usr/share/code/resources/app/out/vs/loader.js:3:12287)
	at Object.<anonymous> (/home/jwiede/.vscode/extensions/tabnine.tabnine-vscode-3.2.15/out/capabilities.js:5:20)
	at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:3:12841)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.s._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27167)
	at Function._._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:23919)
	at Function.W._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/usr/share/code/resources/app/out/vs/loader.js:3:12287)
	at Object.<anonymous> (/home/jwiede/.vscode/extensions/tabnine.tabnine-vscode-3.2.15/out/alphaInstaller.js:6:24)
	at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:3:12841)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.s._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27167)
	at Function._._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:23919)
	at Function.W._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/usr/share/code/resources/app/out/vs/loader.js:3:12287)
	at Object.<anonymous> (/home/jwiede/.vscode/extensions/tabnine.tabnine-vscode-3.2.15/out/extension.js:5:26)
	at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:3:12841)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.s._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27167)
	at Function._._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:23919)
	at Function.W._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at require (internal/modules/cjs/helpers.js:72:18)

**Issue Details:**

**Comment by jwiede** [comment]
One additional note:  Inability to access config or logs unless full recognition model/engine is operational is poor design -- it gives users no means of identifying errors, etc. beyond simple "not working, maybe".  Having at least a command (shift+ctrl+P) to open config panel, instead of relying on editor typing and/or hub isn't "nice to have", it's really a UX necessity, IMO.

**Comment by boaz-codota** [comment]
Thanks for the feedback @jwiede

We do need to improve the messaging to make it easier to understand what platforms we support and what platforms we do not.

If there is anything else I can do to assist you, please let me know.
