### ISSUE TITLE
Intellij Plugin error

### ISSUE THREAD

**Issue by urikjaro** [codota/tabnine-vscode#555]
- Windows  Version	10.0.19043 Build 19043
- IntelliJ IDEA 2021.1.3 (Ultimate Edition) 
    + Build #IU-211.7628.21, built on June 30, 2021 
    +  Runtime version: 11.0.11+9-b1341.60 amd64
    + VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
    + GC: G1 Young Generation, G1 Old Generation;  Memory: 2032M;  Cores: 16
    + Registry: compiler.automake.allow.when.app.running=true, documentation.show.toolbar=true, localHistory.daysToKeep=2
Non-Bundled Plugins: CMD Support (1.0.5), Statistic (4.1.7), com.alayouni.ansiHighlight (1.2.4), com.intellij.ideolog (203.0.27.0), com.jetbrains.darkPurpleTheme (1.2), krasa.IdeaIconPack (1.11), net.seesharpsoft.intellij.plugins.csv (2.16.4), com.ppolivka.plugin.gitcleaner (1.1.4), org.jetbrains.plugins.phpstorm-remote-interpreter (211.6693.65), String Manipulation (8.15.203.000.3), com.euphoricity.gitignore (0.3), ink.organics.pojo2json (1.0.11), net.hexar.json2pojo (1.1.0), org.sonarlint.idea (5.0.1.33703), MavenRunHelper (4.13.203.000.0), com.codota.csp.intellij (4.2.8), org.jetbrains.kotlin (211-1.5.10-release-909-IJ7142.45), com.intellij.gwt (211.6693.65), ru.adelf.idea.dotenv (2021.2), PlantUML integration (5.5.1)
Kotlin: 211-1.5.10-release-909-IJ7142.45

- Lang: Java
- TabNine extension version: com.codota.csp.intellij (4.2.8)

- How to reproduce: change method signature (add enum value) and use new intelliJ function to refactor all occurences (via clicking the "R" on left side near line numbers)

Log:
java.lang.IllegalStateException: Attempt to modify PSI for non-committed Document!
	at com.intellij.pom.core.impl.PomModelImpl.startTransaction(PomModelImpl.java:266)
	at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:93)
	at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:142)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChild(CompositeElement.java:579)
	at com.intellij.psi.impl.source.tree.CompositeElement.addChildren(CompositeElement.java:673)
	at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.addChildren(CodeEditUtil.java:53)
	at com.intellij.psi.impl.source.tree.CompositeElement.addInternal(CompositeElement.java:447)
	at com.intellij.psi.impl.source.tree.JavaSourceUtil.fullyQualifyReference(JavaSourceUtil.java:61)
	at com.intellij.psi.impl.source.tree.java.PsiReferenceExpressionImpl.fullyQualify(PsiReferenceExpressionImpl.java:814)
	at com.intellij.psi.impl.source.codeStyle.JavaReferenceAdjuster.replaceReferenceWithFQ(JavaReferenceAdjuster.java:311)
	at com.intellij.psi.impl.source.codeStyle.JavaReferenceAdjuster.process(JavaReferenceAdjuster.java:105)
	at com.intellij.psi.impl.source.codeStyle.JavaReferenceAdjuster.process(JavaReferenceAdjuster.java:125)
	at com.intellij.psi.impl.source.codeStyle.JavaReferenceAdjuster.process(JavaReferenceAdjuster.java:125)
	at com.intellij.psi.impl.source.codeStyle.JavaCodeStyleManagerImpl.qualifyClassReferences(JavaCodeStyleManagerImpl.java:96)
	at com.intellij.java.refactoring.suggested.JavaSuggestedRefactoringUI$extractValue$$inlined$executeCommand$1$lambda$2$1.run(actions.kt:61)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:959)
	at com.intellij.java.refactoring.suggested.JavaSuggestedRefactoringUI$extractValue$$inlined$executeCommand$1$lambda$2.run(actions.kt:15)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.runUndoTransparentAction(CoreCommandProcessor.java:368)
	at com.intellij.java.refactoring.suggested.JavaSuggestedRefactoringUI$extractValue$$inlined$executeCommand$1.run(actions.kt:18)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:207)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:172)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:162)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:148)
	at com.intellij.java.refactoring.suggested.JavaSuggestedRefactoringUI.extractValue(JavaSuggestedRefactoringUI.kt:70)
	at com.intellij.refactoring.suggested.ParameterValuesPage.getValue(ChangeSignaturePopup.kt:309)
	at com.intellij.refactoring.suggested.ParameterValuesPage.areAllValuesCorrect(ChangeSignaturePopup.kt:291)
	at com.intellij.refactoring.suggested.ChangeSignaturePopup.onParameterValueChanged(ChangeSignaturePopup.kt:133)
	at com.intellij.refactoring.suggested.ChangeSignaturePopup.access$onParameterValueChanged(ChangeSignaturePopup.kt:32)
	at com.intellij.refactoring.suggested.ChangeSignaturePopup$parameterValuesPage$1.invoke(ChangeSignaturePopup.kt:56)
	at com.intellij.refactoring.suggested.ChangeSignaturePopup$parameterValuesPage$1.invoke(ChangeSignaturePopup.kt:32)
	at com.intellij.refactoring.suggested.ParameterValuesPage$initialize$$inlined$apply$lambda$1.get(ChangeSignaturePopup.kt:239)
	at com.intellij.refactoring.suggested.ParameterValuesPage$initialize$$inlined$apply$lambda$1.get(ChangeSignaturePopup.kt:189)
	at com.intellij.openapi.ui.ComponentValidator.revalidate(ComponentValidator.java:199)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.intellij.openapi.ui.ComponentValidator$3.documentChanged(ComponentValidator.java:191)
	at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:916)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:820)
	at com.intellij.openapi.editor.impl.DocumentImpl.insertString(DocumentImpl.java:551)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaretNoScrolling(EditorModificationUtil.java:104)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaret(EditorModificationUtil.java:80)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaret(EditorModificationUtil.java:72)
	at com.intellij.codeInsight.editorActions.TypedHandler.type(TypedHandler.java:256)
	at com.intellij.codeInsight.editorActions.TypedHandler.lambda$doExecute$5(TypedHandler.java:208)
	at com.intellij.openapi.editor.impl.CaretModelImpl.lambda$runForEachCaret$3(CaretModelImpl.java:312)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:421)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:321)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:296)
	at com.intellij.codeInsight.editorActions.TypedHandler.doExecute(TypedHandler.java:165)
	at com.intellij.codeInsight.editorActions.TypedHandler.lambda$execute$0(TypedHandler.java:147)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.codeInsight.editorActions.TypedHandler.execute(TypedHandler.java:147)
	at com.intellij.codeInsight.lookup.impl.LookupTypedHandler.execute(LookupTypedHandler.java:75)
	at com.intellij.codeInsight.template.emmet.EmmetPreviewTypedHandler.execute(EmmetPreviewTypedHandler.java:39)
	at com.intellij.execution.impl.ConsoleViewImpl$MyTypedHandler.execute(ConsoleViewImpl.java:1239)
	at com.codota.intellij.javascript.completion.JSCompletionAutoPopup.execute(SourceFile:32)
	at com.codota.intellij.lean.assistant.completion.local.textual.JavaTextualCompletionsAutoPopup.execute(SourceFile:38)
	at com.intellij.openapi.editor.impl.DefaultRawTypedHandler$1.run(DefaultRawTypedHandler.java:55)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:959)
	at com.intellij.openapi.editor.impl.DefaultRawTypedHandler.execute(DefaultRawTypedHandler.java:49)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl$MyRawTypedHandler.execute(EditorFactoryImpl.java:276)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$2(TypedAction.java:185)
	at com.intellij.reporting.FreezeLoggerImpl.runUnderPerformanceMonitor(FreezeLoggerImpl.java:28)
	at com.intellij.openapi.editor.actionSystem.TypedAction.lambda$actionPerformed$3(TypedAction.java:184)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.editor.actionSystem.TypedAction.actionPerformed(TypedAction.java:184)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTypedNormally(EditorImpl.java:1299)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:1281)
	at com.intellij.openapi.editor.impl.EditorImpl.processKeyTyped(EditorImpl.java:3400)
	at com.intellij.openapi.editor.impl.EditorImpl$7.keyTyped(EditorImpl.java:1120)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6607)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2852)
	at java.desktop/java.awt.Component.processEvent(Component.java:6429)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1962)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:879)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1158)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1018)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:844)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:42)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4908)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:893)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:833)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

gz#2836

**Comment by amircodota** [comment]
@urikjaro It is a little hard to understand the flow that leads to this error.
It would help us a lot if you can provide screenshots or even video.

**Comment by urikjaro** [comment]
@amircodota 
Hi, here is a video when the problem occures. Unfortunately the key presses are not visible - I pressed Ctrl+Space when the popup to define the value of the new variable showed (the screen capture captured only the window itself, not the dropdown)
https://user-images.githubusercontent.com/5805858/124818581-82917e80-df6b-11eb-8986-2aca96971d07.mp4
